// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvc7d4cGMg-YoPcJOh9KL_SeoT_-sA5us',
    appId: '1:872714884514:web:bc50ad6547827e8c750efb',
    messagingSenderId: '872714884514',
    projectId: 'greenstem-mechanics',
    authDomain: 'greenstem-mechanics.firebaseapp.com',
    storageBucket: 'greenstem-mechanics.firebasestorage.app',
    measurementId: 'G-GRDEV2VJJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDVFd3FGUgyXshyu03METo2ICZjEuJqO4',
    appId: '1:872714884514:android:6777898ff23d291d750efb',
    messagingSenderId: '872714884514',
    projectId: 'greenstem-mechanics',
    storageBucket: 'greenstem-mechanics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3pTKcP8OZkf7B14a1OZuc6XZ7aSGNk_A',
    appId: '1:872714884514:ios:dbe95d828697fca2750efb',
    messagingSenderId: '872714884514',
    projectId: 'greenstem-mechanics',
    storageBucket: 'greenstem-mechanics.firebasestorage.app',
    iosBundleId: 'com.example.madAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3pTKcP8OZkf7B14a1OZuc6XZ7aSGNk_A',
    appId: '1:872714884514:ios:dbe95d828697fca2750efb',
    messagingSenderId: '872714884514',
    projectId: 'greenstem-mechanics',
    storageBucket: 'greenstem-mechanics.firebasestorage.app',
    iosBundleId: 'com.example.madAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvc7d4cGMg-YoPcJOh9KL_SeoT_-sA5us',
    appId: '1:872714884514:web:b71ec1a09a508fc6750efb',
    messagingSenderId: '872714884514',
    projectId: 'greenstem-mechanics',
    authDomain: 'greenstem-mechanics.firebaseapp.com',
    storageBucket: 'greenstem-mechanics.firebasestorage.app',
    measurementId: 'G-T6JKG3TTE9',
  );
}
